user=input("Enter Your String ")
print(user[0])
print(user[1])
print(user[2])
print(user[3])
print(user[4])
print(user[5])
print(user[6])
print(user[7])
print(user[8])
print(user[9])
print(user[10])
print(user[11])

print(user[-1])
print(user[-2])
print(user[-3])
print(user[-4])
print(user[-5])
print(user[-6])
print(user[-7])
print(user[-8])
print(user[-9])
print(user[-10])
print(user[-11])